### ISSUE TITLE
モバイル版への移植と再制作の許可をお願い申し上げます

### ISSUE THREAD

**Issue by AngelShadow2017** [danmaq/touhou-ctc-danmakufu#3]
お世話になっております。

突然のご連絡をお許しください。また、GitHubのissueからの連絡となり申し訳ございません。他に連絡手段が見つからなかったため、こちらからご連絡差し上げました。

もし可能であれば（そしてご承諾いただけるのであれば）、貴チームが開発されたゲーム「夢終劇」をモバイル向けに移植・再制作させていただきたく存じます。

私の友人の中にはこのゲームを特に気に入っている者が何人かおり、彼らから強く要望されております。そのため、私一人で「夢終劇」を別のゲームエンジンを使用して再現する計画を立てました。

つきましては、貴チームのご許可をいただけましたら幸いです。貴チームが開発されたゲームは非常に素晴らしく、特に彈幕（ダンマク）はとてもエキサイティングであると感じております。

何卒、よろしくお願い申し上げます。

連絡先メールアドレス:  1509095749@qq.com

**Comment by AngelShadow2017** [comment]
今回の移植・再制作は非営利目的であり、ただ単により多くのプラットフォームでゲームが楽しめるようにすることと、互換性を向上させることが目的です。

**Comment by danmaq** [comment]
ご連絡ありがとうございます。

本作品は [CC-BY-NC-4.0](https://creativecommons.org/licenses/by-nc/4.0/deed.ja) ライセンスで頒布しております。
当該ライセンスの範囲内でご自由に移植やアレンジなどをいただけます。

P.S. もしリリースに至りましたら、ぜひ私にもご宣伝いただけると幸いです。

**Comment by AngelShadow2017** [comment]
我收到了

**Comment by AngelShadow2017** [comment]
> ご連絡ありがとうございます。
> 
> 本作品は [CC-BY-NC-4.0](https://creativecommons.org/licenses/by-nc/4.0/deed.ja) ライセンスで頒布しております。 当該ライセンスの範囲内でご自由に移植やアレンジなどをいただけます。
> 
> P.S. もしリリースに至りましたら、ぜひ私にもご宣伝いただけると幸いです。

このゲームを復刻することができて光栄です。
